---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# Bacula Director configuration

- name: Getting Paths
  action: path_EPS
  changed_when: False
  ignore_errors: yes
  when: path.daemons['bacula-dir']['name']|default("") == ""

- name: Copy bacula-dir.conf file to baculaAdmon Servers to check syntax
  template: src=etc/bacula/bacula-dir.conf.j2 dest=/etc/bacula/.bacula-dir.conf.check owner=root group=bacula mode=0640
  register: checkFile

- name: Check syntax
  shell: "{{ path.commands['bacula-dir'] }} -t -c /etc/bacula/.bacula-dir.conf.check executable='/bin/bash'"
  register: checkResult
  ignore_errors: True
  when: checkFile|changed

- name: if check OK -> Copy bacula-dir.conf file to baculaAdmon Servers
  template: src=etc/bacula/bacula-dir.conf.j2 dest=/etc/bacula/bacula-dir.conf owner=root group=bacula mode=0640 backup=yes
  when: checkFile|changed and checkResult|success

- name: If check fails -> move .bacula-dir.conf.check as .bacula-dir.conf.error
  shell: mv -f /etc/bacula/.bacula-dir.conf.check /etc/bacula/.bacula-dir.conf.error
  when: checkFile|changed and checkResult|failed

- name: Restart bacula-dir systemd
  systemd: name={{ path.daemons['bacula-dir']['name'] }} state=started enabled=true
  when: path.daemons['bacula-dir']['type'] == "systemctl" and checkFile|changed and checkResult|success

- name: Restart bacula-dir service
  service: name={{ path.daemons['bacula-dir']['name'] }} state=started enabled=true
  when: path.daemons['bacula-dir']['type'] == "service" and checkFile|changed and checkResult|success

- name: Restart bacula-dir init
  shell: "{{ path.daemons['bacula-dir']['name'] }} restart executable='/bin/bash'"
  when: path.daemons['bacula-dir']['type'] == "init" and checkFile|changed and checkResult|success
