---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# DHCP (P1) configuration

- name: /etc/dhcp directory permissions
  file: path=/etc/dhcp state=directory owner=root group=manager mode=0750

- name: Copy dhcpd.conf file to DHCP Server to check syntax (P1)
  copy: src=etc/dhcp/dhcpd-P1.conf dest=/etc/dhcp/.dhcpd.conf.check owner=manager group=manager mode=0640
  register: checkFile

- name: Check syntax (P1)
  shell: "dhcpd -t -cf /etc/dhcp/.dhcpd.conf.check executable='/bin/bash'"
  register: checkResult
  ignore_errors: True
  when: checkFile|changed

- name: If check OK -> Copy dhcpd.conf file to DHCP Servers (P1)
  copy: src=etc/dhcp/dhcpd-P1.conf dest=/etc/dhcp/dhcpd.conf owner=manager group=manager mode=0640 backup=yes
  when: checkFile|changed and checkResult|success
  notify: restart dhcp

- name: If check fails -> move .dhcpd.conf.check as .dhcpd.conf.error
  shell: mv -f /etc/dhcp/.dhcpd.conf.check /etc/dhcp/.dhcpd.conf.error
  when: checkFile|changed and checkResult|failed

- name: Getting Service Name
  shell: ( echo "{{ path.daemons.dhcp }}"|sed 's/.*\///' ) 2>/dev/null executable="/bin/bash"
  register: serviceName
  changed_when: False
  ignore_errors: yes
  when: checkFile|changed

- name: Be sure dhcp is running and enabled (P1)
  service: name={{ serviceName.stdout }} state=started enabled=true
  when: checkFile|changed

