---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# CONCURRENCY configuration 

- name: Check if /etc/init.d/rc exists
  stat: path=/etc/init.d/rc
  register: rcfile

- name: Configure concurrency (Debian)
  lineinfile: name=/etc/init.d/rc state=present regexp="^CONCURRENCY=" line="CONCURRENCY={{ concurrency }}" 
  when: rcfile.stat.exists and ansible_os_family == "Debian"
