---
# The source code packaged with this file is Free Software, Copyright (C) 2016 by
# Unidad de Laboratorios, Escuela Politecnica Superior, Universidad de Alicante :: <aeps at eps.ua.es>.
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".


# nscd configuration 

- name: Get python version
  shell: echo {{ ansible_python_version }}|cut -d' ' -f2|cut -d'.' -f1,2
  register: pythonVersion
  changed_when: False

- name: Getting Paths
  action: path_EPS
  changed_when: False
  ignore_errors: yes
  when: path.daemons.nscd.name|default("") == ""

- name: Be sure nscd is installed (Centos)
  yum: pkg=nscd state=installed
  when: ansible_pkg_mgr == "yum"
  
- name: Be sure nscd is installed (Debian and python >= 2.6)
  apt: pkg=nscd state=installed force=yes
  when: ansible_pkg_mgr == "apt" and pythonVersion.stdout|float >= 2.6

- name: Be sure nscd is installed (Debian and python < 2.6)
  #shell: apt-get -y --force-yes install nscd 
  shell: ((apt-cache pkgnames|grep "^nscd$") >/dev/null && echo "No") || ((apt-get -y --force-yes install nscd) && echo "Changed") executable="/bin/bash"
  register: installDebian
  changed_when: installDebian.stdout == "Changed"
  when: ansible_pkg_mgr == "yum" and pythonVersion.stdout|float < 2.6

- name: Configure /etc/nscd.conf file
  copy: src=etc/nscd.conf.{{ ansible_os_family }} dest=/etc/nscd.conf
  register: nscdConf

- name: Restart nscd systemd
  systemd: name={{ path.daemons.nscd.name }} state=restarted enabled=true
  when: path.daemons.nscd.type == "systemctl" and path.daemons.nscd.name != "" and nscdConf|changed 

- name: Restart nscd service
  service: name={{ path.daemons.nscd.name }} state=restarted enabled=true
  when: path.daemons.nscd.type == "service" and path.daemons.nscd.name != "" and nscdConf|changed

- name: Restart nscd init 
  shell: "{{ path.daemons.nscd.name }} restart executable='/bin/bash'"
  when: path.daemons.nscd.type == "init" and path.daemons.nscd.name != "" and nscdConf|changed
